name: Release

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+*'

jobs:
  release_deb_executable:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-24.04
            platform: linux/amd64
          - os: ubuntu-24.04-arm
            platform: linux/arm64
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache Docker layers
        uses: docker/build-push-action@v5
        with:
          context: .github/workflows/
          tags: ubuntu:build
          platforms: ${{ matrix.platform }}
          build-args: IMAGE=ubuntu:20.04
          cache-from: type=gha,scope=ubuntu
          cache-to: type=gha,scope=ubuntu,mode=max
          load: true
      - name: Create deb packages
        run: |
          docker run --rm -i -v $(pwd):/work -w /work ubuntu:build bash -c '/root/.cargo/bin/cargo deb -p recisdb --verbose --output ./artifacts/ -- -F dvb'
      - name: Upload deb package artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-deb-${{ matrix.os }}
          path: ./artifacts/*

  release_windows_exe:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        arch:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
          - aarch64-pc-windows-msvc
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.arch }}
      - uses: MinoruSekine/setup-scoop@v4.0.1
        with:
          apps: llvm cmake git
          scoop_checkup: 'true'
      - name: Install Visual Studio build tools
        shell: cmd
        run: |
          scoop bucket add crystal-preview https://github.com/neatorobito/scoop-crystal
          scoop install vs_2022_cpp_build_tools
      - name: Build
        run: |
          $env:RUSTFLAGS="-C target-feature=+crt-static"
          cargo build --workspace --verbose --release --target ${{ matrix.arch }}
          Rename-Item -Path ./target/${{ matrix.arch }}/release/recisdb.exe recisdb-${{ matrix.arch }}.exe
      - name: Upload exe artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-windows-${{ matrix.arch }}
          path: ./target/${{ matrix.arch }}/release/*.exe

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [release_deb_executable, release_windows_exe]
    permissions:
      contents: write

    steps:
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          pattern: build-*
          path: dist
          merge-multiple: true

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
          files: dist/*
          fail_on_unmatched_files: true
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
